services:
  php81:
    build:
      context: docker/php81
      target: base
    volumes:
      - ./:/app
      - ./vendor-php81:/app/vendor

  php81debug:
    build:
      context: docker/php81
      target: debug
    volumes:
      - ./:/app
      - ./docker/php81:/usr/local/etc/php
      - ./vendor-php81:/app/vendor

  php81composer:
    build:
      context: docker/php81
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php81:/app/vendor

  php82:
    build:
      context: docker/php82
      target: base
    volumes:
      - ./:/app
      - ./vendor-php82:/app/vendor

  php82debug:
    build:
      context: docker/php82
      target: debug
    volumes:
      - ./:/app
      - ./docker/php82:/usr/local/etc/php
      - ./vendor-php82:/app/vendor

  php82composer:
    build:
      context: docker/php82
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php82:/app/vendor

  php83:
    build:
      context: docker/php83
      target: base
    volumes:
      - ./:/app
      - ./vendor-php83:/app/vendor

  php83debug:
    build:
      context: docker/php83
      target: debug
    volumes:
      - ./:/app
      - ./docker/php83:/usr/local/etc/php
      - ./vendor-php83:/app/vendor

  php83composer:
    build:
      context: docker/php83
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php83:/app/vendor

  php84:
    build:
      context: docker/php84
      target: base
    volumes:
      - ./:/app
      - ./vendor-php84:/app/vendor

  php84debug:
    build:
      context: docker/php84
      target: debug
    volumes:
      - ./:/app
      - ./docker/php84:/usr/local/etc/php
      - ./vendor-php84:/app/vendor

  php84composer:
    build:
      context: docker/php84
      target: composer
    volumes:
      - ./:/app
      - ./vendor-php84:/app/vendor

networks:
  default:
    driver: bridge
    labels:
      auto-remove: "true"